<?php

namespace Database\Seeders;

use Attribute;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // seeder

        // // roles user
        // DB::table('roles')->insert([
        //     [
        //         "name"=>"Khách hàng",
        //         "created_at"=> Carbon::now()->toDateTimeString(),
        //         "updated_at"=> Carbon::now()->toDateTimeString()
        //     ],
        //     [
        //         "name"=>"Nhân viên",
        //         "created_at"=> Carbon::now()->toDateTimeString(),
        //         "updated_at"=> Carbon::now()->toDateTimeString()

        //     ],
        //     [
        //         "name"=>"Quản lý",
        //         "created_at"=> Carbon::now()->toDateTimeString(),
        //         "updated_at"=> Carbon::now()->toDateTimeString()

        //     ]
        // ]);

        // // account
        // DB::table('users')->insert([
        //     [
        //         "name"=>"hiep hoang tran",
        //     "email"=>"hieptvh18@gmail.com",
        //     "phone"=>"0123144444",
        //     "role_id"=>3,
        //     "password"=>bcrypt("123123")
        //     ],
        //     [
        //         "name"=>"toi la khach hang",
        //     "email"=>"hipbu18@gmail.com",
        //     "phone"=>"0123144442",
        //     "role_id"=>1,
        //     "password"=>bcrypt("123123")
        //     ]
        // ]);

        // // attribute
        // DB::table('attributes')->insert([
        //     [
        //         "name"=>"Màu sắc"
        //     ],
        //     [
        //         "name"=>"Kích cỡ"
        //     ],
        //     ["name"=>"Chất liệu"]
        // ]);

        // // attr value
        // DB::table('attr_values')->insert([
        //     ["attr_id"=>1,
        //     "name"=>"Đỏ cam",
        //     "value"=>"#ff0000"],
        //     ["attr_id"=>2,
        //     "name"=>"Medium",
        //     "value"=>"M"],
        //     ["attr_id"=>3,
        //     "name"=>"Vải gấm",
        //     "value"=>"Vải gấm"],
        // ]);

        // // web_setting
        // DB::table('web_settings')->insert([
        //     [
        //         'web_name'=>'KOODING',
        //         'intro_title'=>'KOODING Kết nối thời trang Hàn Quốc với bạn
        //         ',
        //         'intro_content'=>'Chào mừng đến với KOODING.com, thị trường toàn cầu trực tuyến hàng đầu. Mục tiêu của chúng tôi là không chỉ kết nối mọi người trên toàn cầu thông qua tình yêu của họ với phong cách Hàn Quốc mà còn mang đến khả năng tiếp cận ngay với thời trang nữ Hàn Quốc mới nhất, thời trang nam Hàn Quốc, các sản phẩm và thương hiệu làm đẹp của Hàn Quốc trên toàn thế giới với chi phí thấp nhất và không rắc rối vận chuyển trên toàn thế giới. Trên tất cả, chúng tôi cố gắng cung cấp cho cộng đồng KOODING những sản phẩm cao cấp được tìm thấy tại các cửa hàng Hàn Quốc với giá cả phải chăng nhất. KOODING cung cấp những mặt hàng quần áo châu Á trực tuyến tốt nhất và là nơi có thể mua sắm bất cứ thứ gì liên quan đến thời trang Hàn Quốc. Từ thời trang đường phố đến quần áo hàng hiệu cao cấp, chúng tôi giúp việc mua sắm trực tuyến của người Hàn Quốc trở nên dễ dàng hơn bao giờ hết. Tại đây, bạn có thể tìm thấy mọi thứ, từ áo hoodie và áo nỉ thoải mái, những chiếc váy đáng yêu, áo khoác và áo len cổ lọ sành điệu và ấm áp, cùng những chiếc quần jean và quần âu mới yêu thích của bạn. Chúng tôi mang các thương hiệu quần áo Hàn Quốc đích thực như Chuu, NANING9, Cherrykoko, BASIC HOUSE, MIND BRIDGE, OPEN THE DOOR, REDHOMME, v.v. Bất kể phong cách ưa thích của bạn là gì, bạn chắc chắn có thể tìm thấy trang phục mơ ước của mình với những bộ quần áo đến từ Hàn Quốc này. KOODING không chỉ là một cửa hàng thời trang trực tuyến của Hàn Quốc; trên thực tế, chúng tôi không chỉ là quần áo phong cách Hàn Quốc và còn cung cấp những sản phẩm K-beauty, album K-pop, đồ trang sức và phụ kiện tốt nhất để hoàn thiện và bổ sung cho mọi khía cạnh trong lối sống của bạn. Các sản phẩm chăm sóc da, mỹ phẩm Hàn Quốc của chúng tôi giúp bạn có được khuôn mặt đẹp nhất của mình. Các thương hiệu như SNP, Ariul, RiRe, Evercell by Chaum, XYZ và MILLION RED là nhà sản xuất công thức cải tiến trong trang điểm và chăm sóc da sử dụng những gì tốt nhất trong bí quyết làm đẹp của Hàn Quốc. Tại đây, bạn có thể mua các loại mặt nạ, sữa rửa mặt, sữa rửa mặt, toner, serum, kem dưỡng da mặt, son tint phong cách Hàn Quốc, phấn nước và mọi thứ khác mà bạn cần để có được vẻ ngoài trang điểm tự nhiên, hoàn thành quy trình chăm sóc da 10 bước, duyệt theo làn da của bạn loại hoặc điều trị mối quan tâm về da của bạn. Hãy đến để tìm ra nơi cuộc sống của bạn đưa bạn đến tại KOODING! Vui lòng duyệt qua trang web của chúng tôi và xem các phong cách thời trang Hàn Quốc mới nhất và tuyệt vời nhất từ ​​cửa hàng thời trang trực tuyến yêu thích mới của bạn. Với khả năng phục vụ hơn 100 quốc gia, chúng tôi đảm bảo bạn sẽ có trải nghiệm mua sắm dễ dàng.',
        //         'logo'=>'627636d057d69-logo1651914448.png',
        //         'fb_url'=>'https://facebook.com',
        //         'insta_url'=>'https://facebook.com',
        //         'twitter_url'=>'https://facebook.com',
        //         'pinterest_url'=>'https://facebook.com',
        //         "created_at"=> Carbon::now()->toDateTimeString(),
        //         "updated_at"=> Carbon::now()->toDateTimeString()

        //     ]
        // ]);

        // // news
        // DB::table('news')->insert([
        //     [
        //         'title'=>'Bộ sưu tập thu đông hot nhất 2021',
        //         'content'=>'Trải qua 12 mùa tổ chức thành công rực rỡ, chương trình Tuần lễ thời trang Quốc tế Việt Nam - Aquafina Vietnam International Fashion Week đã xây dựng nên thương hiệu riêng. 

        //         Phát biểu tại buổi họp báo, bà Trang Lê - Chủ tịch Hiệp hội các Nhà thiết kế thời trang Đông Nam Á (CAFD) kiêm Chủ tịch Aquafina Tuần lễ thời trang Quốc tế Việt Nam đã có những chia sẻ thú vị về thông điệp #ReFashion ý nghĩa năm nay: “Dịch Covid-19 diễn ra trong suốt 2 năm qua đã làm cho cuộc sống của tất cả chúng ta đổi thay. Thời trang thế giới nói chung và thời trang Việt Nam nói riêng cũng không nằm ngoài quy luật thay đổi đó. Chính vì thế, đã đến lúc chúng ta cần thay đổi cách nghĩ (ReThinking), thay đổi cách làm (ReInventing), thay đổi cách vận hành (ReGenerating) để tạo ra một cuộc cách mạng mới (Revolution) nhằm hướng tới sự phát triển bền vững trong thời trang (Sustainable Fashion). Và đó là lý do mà chúng tôi đã quyết định chọn chủ đề năm nay là #ReFashion để truyền đi thông điệp tích cực, hướng đến sự phát triển bền vững cho thời trang Việt Nam trong điều kiện bình thường mới”.',
        //         'image'=>'627698192e496-post-avatar1651939353.jpg',
        //         'short_desc'=>'Cảm hứng thời trang từ kooding mang đến cho mọi người vẻ đẹp lộng lẫy',
        //         'author_id'=>1
        //     ],  
        //     [
        //         'title'=>'Hé lộ nhà thiết kế tham dự Tuần lễ thời trang Quốc tế Việt Nam 2022',
        //         'content'=>'Trải qua 12 mùa tổ chức thành công rực rỡ, chương trình Tuần lễ thời trang Quốc tế Việt Nam - Aquafina Vietnam International Fashion Week đã xây dựng nên thương hiệu riêng. 

        //         Phát biểu tại buổi họp báo, bà Trang Lê - Chủ tịch Hiệp hội các Nhà thiết kế thời trang Đông Nam Á (CAFD) kiêm Chủ tịch Aquafina Tuần lễ thời trang Quốc tế Việt Nam đã có những chia sẻ thú vị về thông điệp #ReFashion ý nghĩa năm nay: “Dịch Covid-19 diễn ra trong suốt 2 năm qua đã làm cho cuộc sống của tất cả chúng ta đổi thay. Thời trang thế giới nói chung và thời trang Việt Nam nói riêng cũng không nằm ngoài quy luật thay đổi đó. Chính vì thế, đã đến lúc chúng ta cần thay đổi cách nghĩ (ReThinking), thay đổi cách làm (ReInventing), thay đổi cách vận hành (ReGenerating) để tạo ra một cuộc cách mạng mới (Revolution) nhằm hướng tới sự phát triển bền vững trong thời trang (Sustainable Fashion). Và đó là lý do mà chúng tôi đã quyết định chọn chủ đề năm nay là #ReFashion để truyền đi thông điệp tích cực, hướng đến sự phát triển bền vững cho thời trang Việt Nam trong điều kiện bình thường mới”.',
        //         'image'=>'627698192e496-post-avatar1651939353.jpg',
        //         'short_desc'=>'Hé lộ nhà thiết kế tham dự Tuần lễ thời trang Quốc tế Việt Nam 2022',
        //         'author_id'=>1
        //     ],
        //     [
        //         'title'=>'Levi tôn vinh dòng sản phẩm 501 huyền thoại với loạt ngôi sao trẻ',
        //         'content'=>'Trải qua 12 mùa tổ chức thành công rực rỡ, chương trình Tuần lễ thời trang Quốc tế Việt Nam - Aquafina Vietnam International Fashion Week đã xây dựng nên thương hiệu riêng. 

        //         Phát biểu tại buổi họp báo, bà Trang Lê - Chủ tịch Hiệp hội các Nhà thiết kế thời trang Đông Nam Á (CAFD) kiêm Chủ tịch Aquafina Tuần lễ thời trang Quốc tế Việt Nam đã có những chia sẻ thú vị về thông điệp #ReFashion ý nghĩa năm nay: “Dịch Covid-19 diễn ra trong suốt 2 năm qua đã làm cho cuộc sống của tất cả chúng ta đổi thay. Thời trang thế giới nói chung và thời trang Việt Nam nói riêng cũng không nằm ngoài quy luật thay đổi đó. Chính vì thế, đã đến lúc chúng ta cần thay đổi cách nghĩ (ReThinking), thay đổi cách làm (ReInventing), thay đổi cách vận hành (ReGenerating) để tạo ra một cuộc cách mạng mới (Revolution) nhằm hướng tới sự phát triển bền vững trong thời trang (Sustainable Fashion). Và đó là lý do mà chúng tôi đã quyết định chọn chủ đề năm nay là #ReFashion để truyền đi thông điệp tích cực, hướng đến sự phát triển bền vững cho thời trang Việt Nam trong điều kiện bình thường mới”.',
        //         'image'=>'627644ff8e70d-category1651918079.jpg',
        //         'short_desc'=>'Hé lộ nhà thiết kế tham dự Tuần lễ thời trang Quốc tế Việt Nam 2022',
        //         'author_id'=>1
        //     ]
        // ]);

        // // brand+ product
        // \App\Models\Brand::factory(5)->create();
        // \App\Models\Category::factory(3)->create();
        // \App\Models\Product::factory(15)->create();


        //  hanh chinh viet nam render data display checkout

        DB::table('province')->insert([
            ['01TTT' => 'Thành phố Hà Nội'],
            ['02TTT' => 'Tỉnh Hà Giang'],
            ['04TTT' => 'Tỉnh Cao Bằng'],
            ['06TTT' => 'Tỉnh Bắc Kạn'],
            ['08TTT' => 'Tỉnh Tuyên Quang'],
            ['10TTT' => 'Tỉnh Lào Cai'],
            ['11TTT' => 'Tỉnh Điện Biên'],
            ['12TTT' => 'Tỉnh Lai Châu'],
            ['14TTT' => 'Tỉnh Sơn La'],
            ['15TTT' => 'Tỉnh Yên Bái'],
            ['17TTT' => 'Tỉnh Hòa Bình'],
            ['19TTT' => 'Tỉnh Thái Nguyên'],
            ['20TTT' => 'Tỉnh Lạng Sơn'],
            ['22TTT' => 'Tỉnh Quảng Ninh'],
            ['24TTT' => 'Tỉnh Bắc Giang'],
            ['25TTT' => 'Tỉnh Phú Thọ'],
            ['26TTT' => 'Tỉnh Vĩnh Phúc'],
            ['27TTT' => 'Tỉnh Bắc Ninh'],
            ['30TTT' => 'Tỉnh Hải Dương'],
            ['31TTT' => 'Thành phố Hải Phòng'],
            ['33TTT' => 'Tỉnh Hưng Yên'],
            ['34TTT' => 'Tỉnh Thái Bình'],
            ['35TTT' => 'Tỉnh Hà Nam'],
            ['36TTT' => 'Tỉnh Nam Định'],
            ['37TTT' => 'Tỉnh Ninh Bình'],
            ['38TTT' => 'Tỉnh Thanh Hóa'],
            ['40TTT' => 'Tỉnh Nghệ An'],
            ['42TTT' => 'Tỉnh Hà Tĩnh'],
            ['44TTT' => 'Tỉnh Quảng Bình'],
            ['45TTT' => 'Tỉnh Quảng Trị'],
            ['46TTT' => 'Tỉnh Thừa Thiên Huế'],
            ['48TTT' => 'Thành phố Đà Nẵng'],
            ['49TTT' => 'Tỉnh Quảng Nam'],
            ['51TTT' => 'Tỉnh Quảng Ngãi'],
            ['52TTT' => 'Tỉnh Bình Định'],
            ['54TTT' => 'Tỉnh Phú Yên'],
            ['56TTT' => 'Tỉnh Khánh Hòa'],
            ['58TTT' => 'Tỉnh Ninh Thuận'],
            ['60TTT' => 'Tỉnh Bình Thuận'],
            ['62TTT' => 'Tỉnh Kon Tum'],
            ['64TTT' => 'Tỉnh Gia Lai'],
            ['66TTT' => 'Tỉnh Đắk Lắk'],
            ['67TTT' => 'Tỉnh Đắk Nông'],
            ['68TTT' => 'Tỉnh Lâm Đồng'],
            ['70TTT' => 'Tỉnh Bình Phước'],
            ['72TTT' => 'Tỉnh Tây Ninh'],
            ['74TTT' => 'Tỉnh Bình Dương'],
            ['75TTT' => 'Tỉnh Đồng Nai'],
            ['77TTT' => 'Tỉnh Bà Rịa - Vũng Tàu'],
            ['79TTT' => 'Thành phố Hồ Chí Minh'],
            ['80TTT' => 'Tỉnh Long An'],
            ['82TTT' => 'Tỉnh Tiền Giang'],
            ['83TTT' => 'Tỉnh Bến Tre'],
            ['84TTT' => 'Tỉnh Trà Vinh'],
            ['86TTT' => 'Tỉnh Vĩnh Long'],
            ['87TTT' => 'Tỉnh Đồng Tháp'],
            ['89TTT' => 'Tỉnh An Giang'],
            ['91TTT' => 'Tỉnh Kiên Giang'],
            ['92TTT' => 'Thành phố Cần Thơ'],
            ['93TTT' => 'Tỉnh Hậu Giang'],
            ['94TTT' => 'Tỉnh Sóc Trăng'],
            ['95TTT' => 'Tỉnh Bạc Liêu'],
            ['96TTT' => 'Tỉnh Cà Mau']
        ]);

        DB::table('district')->insert([
            ['districtid' => '001HH', 'name' => 'Quận Ba Đình', 'provinceid' => '01TTT'],
            ['districtid' => '002HH', 'name' => 'Quận Hoàn Kiếm', 'provinceid' => '01TTT'],
            ['districtid' => '003HH', 'name' => 'Quận Tây Hồ', 'provinceid' => '01TTT'],
            ['districtid' => '004HH', 'name' => 'Quận Long Biên', 'provinceid' => '01TTT'],
            ['districtid' => '005HH', 'name' => 'Quận Cầu Giấy', 'provinceid' => '01TTT'],
            ['districtid' => '006HH', 'name' => 'Quận Đống Đa', 'provinceid' => '01TTT'],
            ['districtid' => '007HH', 'name' => 'Quận Hai Bà Trưng', 'provinceid' => '01TTT'],
            ['districtid' => '008HH', 'name' => 'Quận Hoàng Mai', 'provinceid' => '01TTT'],
            ['districtid' => '009HH', 'name' => 'Quận Thanh Xuân', 'provinceid' => '01TTT'],
            ['districtid' => '016HH', 'name' => 'Huyện Sóc Sơn', 'provinceid' => '01TTT'],
            ['districtid' => '017HH', 'name' => 'Huyện Đông Anh', 'provinceid' => '01TTT'],
            ['districtid' => '018HH', 'name' => 'Huyện Gia Lâm', 'provinceid' => '01TTT'],
            ['districtid' => '019HH', 'name' => 'Quận Nam Từ Liêm', 'provinceid' => '01TTT'],
            ['districtid' => '020HH', 'name' => 'Huyện Thanh Trì', 'provinceid' => '01TTT'],
            ['districtid' => '021HH', 'name' => 'Quận Bắc Từ Liêm', 'provinceid' => '01TTT'],
            ['districtid' => '024HH', 'name' => 'Thành phố Hà Giang', 'provinceid' => '02TTT'],
            ['districtid' => '026HH', 'name' => 'Huyện Đồng Văn', 'provinceid' => '02TTT'],
            ['districtid' => '027HH', 'name' => 'Huyện Mèo Vạc', 'provinceid' => '02TTT'],
            ['districtid' => '028HH', 'name' => 'Huyện Yên Minh', 'provinceid' => '02TTT'],
            ['districtid' => '029HH', 'name' => 'Huyện Quản Bạ', 'provinceid' => '02TTT'],
            ['districtid' => '030HH', 'name' => 'Huyện Vị Xuyên', 'provinceid' => '02TTT'],
            ['districtid' => '031HH', 'name' => 'Huyện Bắc Mê', 'provinceid' => '02TTT'],
            ['districtid' => '032HH', 'name' => 'Huyện Hoàng Su Phì', 'provinceid' => '02TTT'],
            ['districtid' => '033HH', 'name' => 'Huyện Xín Mần', 'provinceid' => '02TTT'],
            ['districtid' => '034HH', 'name' => 'Huyện Bắc Quang', 'provinceid' => '02TTT'],
            ['districtid' => '035HH', 'name' => 'Huyện Quang Bình', 'provinceid' => '02TTT'],
            ['districtid' => '040HH', 'name' => 'Thành phố Cao Bằng', 'provinceid' => '04TTT'],
            ['districtid' => '042HH', 'name' => 'Huyện Bảo Lâm', 'provinceid' => '04TTT'],
            ['districtid' => '043HH', 'name' => 'Huyện Bảo Lạc', 'provinceid' => '04TTT'],
            ['districtid' => '044HH', 'name' => 'Huyện Thông Nông', 'provinceid' => '04TTT'],
            ['districtid' => '045HH', 'name' => 'Huyện Hà Quảng', 'provinceid' => '04TTT'],
            ['districtid' => '046HH', 'name' => 'Huyện Trà Lĩnh', 'provinceid' => '04TTT'],
            ['districtid' => '047HH', 'name' => 'Huyện Trùng Khánh', 'provinceid' => '04TTT'],
            ['districtid' => '048HH', 'name' => 'Huyện Hạ Lang', 'provinceid' => '04TTT'],
            ['districtid' => '049HH', 'name' => 'Huyện Quảng Uyên', 'provinceid' => '04TTT'],
            ['districtid' => '050HH', 'name' => 'Huyện Phục Hòa', 'provinceid' => '04TTT'],
            ['districtid' => '051HH', 'name' => 'Huyện Hòa An', 'provinceid' => '04TTT'],
            ['districtid' => '052HH', 'name' => 'Huyện Nguyên Bình', 'provinceid' => '04TTT'],
            ['districtid' => '053HH', 'name' => 'Huyện Thạch An', 'provinceid' => '04TTT'],
            ['districtid' => '058HH', 'name' => 'Thành Phố Bắc Kạn', 'provinceid' => '06TTT'],
            ['districtid' => '060HH', 'name' => 'Huyện Pác Nặm', 'provinceid' => '06TTT'],
            ['districtid' => '061HH', 'name' => 'Huyện Ba Bể', 'provinceid' => '06TTT'],
            ['districtid' => '062HH', 'name' => 'Huyện Ngân Sơn', 'provinceid' => '06TTT'],
            ['districtid' => '063HH', 'name' => 'Huyện Bạch Thông', 'provinceid' => '06TTT'],
            ['districtid' => '064HH', 'name' => 'Huyện Chợ Đồn', 'provinceid' => '06TTT'],
            ['districtid' => '065HH', 'name' => 'Huyện Chợ Mới', 'provinceid' => '06TTT'],
            ['districtid' => '066HH', 'name' => 'Huyện Na Rì', 'provinceid' => '06TTT'],
            ['districtid' => '070HH', 'name' => 'Thành phố Tuyên Quang', 'provinceid' => '08TTT'],
            ['districtid' => '071HH', 'name' => 'Huyện Lâm Bình', 'provinceid' => '08TTT'],
            ['districtid' => '072HH', 'name' => 'Huyện Na Hang', 'provinceid' => '08TTT'],
            ['districtid' => '073HH', 'name' => 'Huyện Chiêm Hóa', 'provinceid' => '08TTT'],
            ['districtid' => '074HH', 'name' => 'Huyện Hàm Yên', 'provinceid' => '08TTT'],
            ['districtid' => '075HH', 'name' => 'Huyện Yên Sơn', 'provinceid' => '08TTT'],
            ['districtid' => '076HH', 'name' => 'Huyện Sơn Dương', 'provinceid' => '08TTT'],
            ['districtid' => '080HH', 'name' => 'Thành phố Lào Cai', 'provinceid' => '10TTT'],
            ['districtid' => '082HH', 'name' => 'Huyện Bát Xát', 'provinceid' => '10TTT'],
            ['districtid' => '083HH', 'name' => 'Huyện Mường Khương', 'provinceid' => '10TTT'],
            ['districtid' => '084HH', 'name' => 'Huyện Si Ma Cai', 'provinceid' => '10TTT'],
            ['districtid' => '085HH', 'name' => 'Huyện Bắc Hà', 'provinceid' => '10TTT'],
            ['districtid' => '086HH', 'name' => 'Huyện Bảo Thắng', 'provinceid' => '10TTT'],
            ['districtid' => '087HH', 'name' => 'Huyện Bảo Yên', 'provinceid' => '10TTT'],
            ['districtid' => '088HH', 'name' => 'Huyện Sa Pa', 'provinceid' => '10TTT'],
            ['districtid' => '089HH', 'name' => 'Huyện Văn Bàn', 'provinceid' => '10TTT'],
            ['districtid' => '094HH', 'name' => 'Thành phố Điện Biên Phủ', 'provinceid' => '11TTT'],
            ['districtid' => '095HH', 'name' => 'Thị Xã Mường Lay', 'provinceid' => '11TTT'],
            ['districtid' => '096HH', 'name' => 'Huyện Mường Nhé', 'provinceid' => '11TTT'],
            ['districtid' => '097HH', 'name' => 'Huyện Mường Chà', 'provinceid' => '11TTT'],
            ['districtid' => '098HH', 'name' => 'Huyện Tủa Chùa', 'provinceid' => '11TTT'],
            ['districtid' => '099HH', 'name' => 'Huyện Tuần Giáo', 'provinceid' => '11TTT'],
            ['districtid' => '100HH', 'name' => 'Huyện Điện Biên', 'provinceid' => '11TTT'],
            ['districtid' => '101HH', 'name' => 'Huyện Điện Biên Đông', 'provinceid' => '11TTT'],
            ['districtid' => '102HH', 'name' => 'Huyện Mường Ảng', 'provinceid' => '11TTT'],
            ['districtid' => '103HH', 'name' => 'Huyện Nậm Pồ', 'provinceid' => '11TTT'],
            ['districtid' => '105HH', 'name' => 'Thành phố Lai Châu', 'provinceid' => '12TTT'],
            ['districtid' => '106HH', 'name' => 'Huyện Tam Đường', 'provinceid' => '12TTT'],
            ['districtid' => '107HH', 'name' => 'Huyện Mường Tè', 'provinceid' => '12TTT'],
            ['districtid' => '108HH', 'name' => 'Huyện Sìn Hồ', 'provinceid' => '12TTT'],
            ['districtid' => '109HH', 'name' => 'Huyện Phong Thổ', 'provinceid' => '12TTT'],
            ['districtid' => '110HH', 'name' => 'Huyện Than Uyên', 'provinceid' => '12TTT'],
            ['districtid' => '111HH', 'name' => 'Huyện Tân Uyên', 'provinceid' => '12TTT'],
            ['districtid' => '112HH', 'name' => 'Huyện Nậm Nhùn', 'provinceid' => '12TTT'],
            ['districtid' => '116HH', 'name' => 'Thành phố Sơn La', 'provinceid' => '14TTT'],
            ['districtid' => '118HH', 'name' => 'Huyện Quỳnh Nhai', 'provinceid' => '14TTT'],
            ['districtid' => '119HH', 'name' => 'Huyện Thuận Châu', 'provinceid' => '14TTT'],
            ['districtid' => '120HH', 'name' => 'Huyện Mường La', 'provinceid' => '14TTT'],
            ['districtid' => '121HH', 'name' => 'Huyện Bắc Yên', 'provinceid' => '14TTT'],
            ['districtid' => '122HH', 'name' => 'Huyện Phù Yên', 'provinceid' => '14TTT'],
            ['districtid' => '123HH', 'name' => 'Huyện Mộc Châu', 'provinceid' => '14TTT'],
            ['districtid' => '124HH', 'name' => 'Huyện Yên Châu', 'provinceid' => '14TTT'],
            ['districtid' => '125HH', 'name' => 'Huyện Mai Sơn', 'provinceid' => '14TTT'],
            ['districtid' => '126HH', 'name' => 'Huyện Sông Mã', 'provinceid' => '14TTT'],
            ['districtid' => '127HH', 'name' => 'Huyện Sốp Cộp', 'provinceid' => '14TTT'],
            ['districtid' => '128HH', 'name' => 'Huyện Vân Hồ', 'provinceid' => '14TTT'],
            ['districtid' => '132HH', 'name' => 'Thành phố Yên Bái', 'provinceid' => '15TTT'],
            ['districtid' => '133HH', 'name' => 'Thị xã Nghĩa Lộ', 'provinceid' => '15TTT'],
            ['districtid' => '135HH', 'name' => 'Huyện Lục Yên', 'provinceid' => '15TTT'],
            ['districtid' => '136HH', 'name' => 'Huyện Văn Yên', 'provinceid' => '15TTT'],
            ['districtid' => '137HH', 'name' => 'Huyện Mù Căng Chải', 'provinceid' => '15TTT'],
            ['districtid' => '138HH', 'name' => 'Huyện Trấn Yên', 'provinceid' => '15TTT'],
            ['districtid' => '139HH', 'name' => 'Huyện Trạm Tấu', 'provinceid' => '15TTT'],
            ['districtid' => '140HH', 'name' => 'Huyện Văn Chấn', 'provinceid' => '15TTT'],
            ['districtid' => '141HH', 'name' => 'Huyện Yên Bình', 'provinceid' => '15TTT'],
            ['districtid' => '148HH', 'name' => 'Thành phố Hòa Bình', 'provinceid' => '17TTT'],
            ['districtid' => '150HH', 'name' => 'Huyện Đà Bắc', 'provinceid' => '17TTT'],
            ['districtid' => '151HH', 'name' => 'Huyện Kỳ Sơn', 'provinceid' => '17TTT'],
            ['districtid' => '152HH', 'name' => 'Huyện Lương Sơn', 'provinceid' => '17TTT'],
            ['districtid' => '153HH', 'name' => 'Huyện Kim Bôi', 'provinceid' => '17TTT'],
            ['districtid' => '154HH', 'name' => 'Huyện Cao Phong', 'provinceid' => '17TTT'],
            ['districtid' => '155HH', 'name' => 'Huyện Tân Lạc', 'provinceid' => '17TTT'],
            ['districtid' => '156HH', 'name' => 'Huyện Mai Châu', 'provinceid' => '17TTT'],
            ['districtid' => '157HH', 'name' => 'Huyện Lạc Sơn', 'provinceid' => '17TTT'],
            ['districtid' => '158HH', 'name' => 'Huyện Yên Thủy', 'provinceid' => '17TTT'],
            ['districtid' => '159HH', 'name' => 'Huyện Lạc Thủy', 'provinceid' => '17TTT'],
            ['districtid' => '164HH', 'name' => 'Thành phố Thái Nguyên', 'provinceid' => '19TTT'],
            ['districtid' => '165HH', 'name' => 'Thành phố Sông Công', 'provinceid' => '19TTT'],
            ['districtid' => '167HH', 'name' => 'Huyện Định Hóa', 'provinceid' => '19TTT'],
            ['districtid' => '168HH', 'name' => 'Huyện Phú Lương', 'provinceid' => '19TTT'],
            ['districtid' => '169HH', 'name' => 'Huyện Đồng Hỷ', 'provinceid' => '19TTT'],
            ['districtid' => '170HH', 'name' => 'Huyện Võ Nhai', 'provinceid' => '19TTT'],
            ['districtid' => '171HH', 'name' => 'Huyện Đại Từ', 'provinceid' => '19TTT'],
            ['districtid' => '172HH', 'name' => 'Thị xã Phổ Yên', 'provinceid' => '19TTT'],
            ['districtid' => '173HH', 'name' => 'Huyện Phú Bình', 'provinceid' => '19TTT'],
            ['districtid' => '178HH', 'name' => 'Thành phố Lạng Sơn', 'provinceid' => '20TTT'],
            ['districtid' => '180HH', 'name' => 'Huyện Tràng Định', 'provinceid' => '20TTT'],
            ['districtid' => '181HH', 'name' => 'Huyện Bình Gia', 'provinceid' => '20TTT'],
            ['districtid' => '182HH', 'name' => 'Huyện Văn Lãng', 'provinceid' => '20TTT'],
            ['districtid' => '183HH', 'name' => 'Huyện Cao Lộc', 'provinceid' => '20TTT'],
            ['districtid' => '184HH', 'name' => 'Huyện Văn Quan', 'provinceid' => '20TTT'],
            ['districtid' => '185HH', 'name' => 'Huyện Bắc Sơn', 'provinceid' => '20TTT'],
            ['districtid' => '186HH', 'name' => 'Huyện Hữu Lũng', 'provinceid' => '20TTT'],
            ['districtid' => '187HH', 'name' => 'Huyện Chi Lăng', 'provinceid' => '20TTT'],
            ['districtid' => '188HH', 'name' => 'Huyện Lộc Bình', 'provinceid' => '20TTT'],
            ['districtid' => '189HH', 'name' => 'Huyện Đình Lập', 'provinceid' => '20TTT'],
            ['districtid' => '193HH', 'name' => 'Thành phố Hạ Long', 'provinceid' => '22TTT'],
            ['districtid' => '194HH', 'name' => 'Thành phố Móng Cái', 'provinceid' => '22TTT'],
            ['districtid' => '195HH', 'name' => 'Thành phố Cẩm Phả', 'provinceid' => '22TTT'],
            ['districtid' => '196HH', 'name' => 'Thành phố Uông Bí', 'provinceid' => '22TTT'],
            ['districtid' => '198HH', 'name' => 'Huyện Bình Liêu', 'provinceid' => '22TTT'],
            ['districtid' => '199HH', 'name' => 'Huyện Tiên Yên', 'provinceid' => '22TTT'],
            ['districtid' => '200HH', 'name' => 'Huyện Đầm Hà', 'provinceid' => '22TTT'],
            ['districtid' => '201HH', 'name' => 'Huyện Hải Hà', 'provinceid' => '22TTT'],
            ['districtid' => '202HH', 'name' => 'Huyện Ba Chẽ', 'provinceid' => '22TTT'],
            ['districtid' => '203HH', 'name' => 'Huyện Vân Đồn', 'provinceid' => '22TTT'],
            ['districtid' => '204HH', 'name' => 'Huyện Hoành Bồ', 'provinceid' => '22TTT'],
            ['districtid' => '205HH', 'name' => 'Thị xã Đông Triều', 'provinceid' => '22TTT'],
            ['districtid' => '206HH', 'name' => 'Thị xã Quảng Yên', 'provinceid' => '22TTT'],
            ['districtid' => '207HH', 'name' => 'Huyện Cô Tô', 'provinceid' => '22TTT'],
            ['districtid' => '213HH', 'name' => 'Thành phố Bắc Giang', 'provinceid' => '24TTT'],
            ['districtid' => '215HH', 'name' => 'Huyện Yên Thế', 'provinceid' => '24TTT'],
            ['districtid' => '216HH', 'name' => 'Huyện Tân Yên', 'provinceid' => '24TTT'],
            ['districtid' => '217HH', 'name' => 'Huyện Lạng Giang', 'provinceid' => '24TTT'],
            ['districtid' => '218HH', 'name' => 'Huyện Lục Nam', 'provinceid' => '24TTT'],
            ['districtid' => '219HH', 'name' => 'Huyện Lục Ngạn', 'provinceid' => '24TTT'],
            ['districtid' => '220HH', 'name' => 'Huyện Sơn Động', 'provinceid' => '24TTT'],
            ['districtid' => '221HH', 'name' => 'Huyện Yên Dũng', 'provinceid' => '24TTT'],
            ['districtid' => '222HH', 'name' => 'Huyện Việt Yên', 'provinceid' => '24TTT'],
            ['districtid' => '223HH', 'name' => 'Huyện Hiệp Hòa', 'provinceid' => '24TTT'],
            ['districtid' => '227HH', 'name' => 'Thành phố Việt Trì', 'provinceid' => '25TTT'],
            ['districtid' => '228HH', 'name' => 'Thị xã Phú Thọ', 'provinceid' => '25TTT'],
            ['districtid' => '230HH', 'name' => 'Huyện Đoan Hùng', 'provinceid' => '25TTT'],
            ['districtid' => '231HH', 'name' => 'Huyện Hạ Hòa', 'provinceid' => '25TTT'],
            ['districtid' => '232HH', 'name' => 'Huyện Thanh Ba', 'provinceid' => '25TTT'],
            ['districtid' => '233HH', 'name' => 'Huyện Phù Ninh', 'provinceid' => '25TTT'],
            ['districtid' => '234HH', 'name' => 'Huyện Yên Lập', 'provinceid' => '25TTT'],
            ['districtid' => '235HH', 'name' => 'Huyện Cẩm Khê', 'provinceid' => '25TTT'],
            ['districtid' => '236HH', 'name' => 'Huyện Tam Nông', 'provinceid' => '25TTT'],
            ['districtid' => '237HH', 'name' => 'Huyện Lâm Thao', 'provinceid' => '25TTT'],
            ['districtid' => '238HH', 'name' => 'Huyện Thanh Sơn', 'provinceid' => '25TTT'],
            ['districtid' => '239HH', 'name' => 'Huyện Thanh Thuỷ', 'provinceid' => '25TTT'],
            ['districtid' => '240HH', 'name' => 'Huyện Tân Sơn', 'provinceid' => '25TTT'],
            ['districtid' => '243HH', 'name' => 'Thành phố Vĩnh Yên', 'provinceid' => '26TTT'],
            ['districtid' => '244HH', 'name' => 'Thị xã Phúc Yên', 'provinceid' => '26TTT'],
            ['districtid' => '246HH', 'name' => 'Huyện Lập Thạch', 'provinceid' => '26TTT'],
            ['districtid' => '247HH', 'name' => 'Huyện Tam Dương', 'provinceid' => '26TTT'],
            ['districtid' => '248HH', 'name' => 'Huyện Tam Đảo', 'provinceid' => '26TTT'],
            ['districtid' => '249HH', 'name' => 'Huyện Bình Xuyên', 'provinceid' => '26TTT'],
            ['districtid' => '250HH', 'name' => 'Huyện Mê Linh', 'provinceid' => '01TTT'],
            ['districtid' => '251HH', 'name' => 'Huyện Yên Lạc', 'provinceid' => '26TTT'],
            ['districtid' => '252HH', 'name' => 'Huyện Vĩnh Tường', 'provinceid' => '26TTT'],
            ['districtid' => '253HH', 'name' => 'Huyện Sông Lô', 'provinceid' => '26TTT'],
            ['districtid' => '256HH', 'name' => 'Thành phố Bắc Ninh', 'provinceid' => '27TTT'],
            ['districtid' => '258HH', 'name' => 'Huyện Yên Phong', 'provinceid' => '27TTT'],
            ['districtid' => '259HH', 'name' => 'Huyện Quế Võ', 'provinceid' => '27TTT'],
            ['districtid' => '260HH', 'name' => 'Huyện Tiên Du', 'provinceid' => '27TTT'],
            ['districtid' => '261HH', 'name' => 'Thị xã Từ Sơn', 'provinceid' => '27TTT'],
            ['districtid' => '262HH', 'name' => 'Huyện Thuận Thành', 'provinceid' => '27TTT'],
            ['districtid' => '263HH', 'name' => 'Huyện Gia Bình', 'provinceid' => '27TTT'],
            ['districtid' => '264HH', 'name' => 'Huyện Lương Tài', 'provinceid' => '27TTT'],
            ['districtid' => '268HH', 'name' => 'Quận Hà Đông', 'provinceid' => '01TTT'],
            ['districtid' => '269HH', 'name' => 'Thị xã Sơn Tây', 'provinceid' => '01TTT'],
            ['districtid' => '271HH', 'name' => 'Huyện Ba Vì', 'provinceid' => '01TTT'],
            ['districtid' => '272HH', 'name' => 'Huyện Phúc Thọ', 'provinceid' => '01TTT'],
            ['districtid' => '273HH', 'name' => 'Huyện Đan Phượng', 'provinceid' => '01TTT'],
            ['districtid' => '274HH', 'name' => 'Huyện Hoài Đức', 'provinceid' => '01TTT'],
            ['districtid' => '275HH', 'name' => 'Huyện Quốc Oai', 'provinceid' => '01TTT'],
            ['districtid' => '276HH', 'name' => 'Huyện Thạch Thất', 'provinceid' => '01TTT'],
            ['districtid' => '277HH', 'name' => 'Huyện Chương Mỹ', 'provinceid' => '01TTT'],
            ['districtid' => '278HH', 'name' => 'Huyện Thanh Oai', 'provinceid' => '01TTT'],
            ['districtid' => '279HH', 'name' => 'Huyện Thường Tín', 'provinceid' => '01TTT'],
            ['districtid' => '280HH', 'name' => 'Huyện Phú Xuyên', 'provinceid' => '01TTT'],
            ['districtid' => '281HH', 'name' => 'Huyện Ứng Hòa', 'provinceid' => '01TTT'],
            ['districtid' => '282HH', 'name' => 'Huyện Mỹ Đức', 'provinceid' => '01TTT'],
            ['districtid' => '288HH', 'name' => 'Thành phố Hải Dương', 'provinceid' => '30TTT'],
            ['districtid' => '290HH', 'name' => 'Thị xã Chí Linh', 'provinceid' => '30TTT'],
            ['districtid' => '291HH', 'name' => 'Huyện Nam Sách', 'provinceid' => '30TTT'],
            ['districtid' => '292HH', 'name' => 'Huyện Kinh Môn', 'provinceid' => '30TTT'],
            ['districtid' => '293HH', 'name' => 'Huyện Kim Thành', 'provinceid' => '30TTT'],
            ['districtid' => '294HH', 'name' => 'Huyện Thanh Hà', 'provinceid' => '30TTT'],
            ['districtid' => '295HH', 'name' => 'Huyện Cẩm Giàng', 'provinceid' => '30TTT'],
            ['districtid' => '296HH', 'name' => 'Huyện Bình Giang', 'provinceid' => '30TTT'],
            ['districtid' => '297HH', 'name' => 'Huyện Gia Lộc', 'provinceid' => '30TTT'],
            ['districtid' => '298HH', 'name' => 'Huyện Tứ Kỳ', 'provinceid' => '30TTT'],
            ['districtid' => '299HH', 'name' => 'Huyện Ninh Giang', 'provinceid' => '30TTT'],
            ['districtid' => '300HH', 'name' => 'Huyện Thanh Miện', 'provinceid' => '30TTT'],
            ['districtid' => '303HH', 'name' => 'Quận Hồng Bàng', 'provinceid' => '31TTT'],
            ['districtid' => '304HH', 'name' => 'Quận Ngô Quyền', 'provinceid' => '31TTT'],
            ['districtid' => '305HH', 'name' => 'Quận Lê Chân', 'provinceid' => '31TTT'],
            ['districtid' => '306HH', 'name' => 'Quận Hải An', 'provinceid' => '31TTT'],
            ['districtid' => '307HH', 'name' => 'Quận Kiến An', 'provinceid' => '31TTT'],
            ['districtid' => '308HH', 'name' => 'Quận Đồ Sơn', 'provinceid' => '31TTT'],
            ['districtid' => '309HH', 'name' => 'Quận Dương Kinh', 'provinceid' => '31TTT'],
            ['districtid' => '311HH', 'name' => 'Huyện Thủy Nguyên', 'provinceid' => '31TTT'],
            ['districtid' => '312HH', 'name' => 'Huyện An Dương', 'provinceid' => '31TTT'],
            ['districtid' => '313HH', 'name' => 'Huyện An Lão', 'provinceid' => '31TTT'],
            ['districtid' => '314HH', 'name' => 'Huyện Kiến Thuỵ', 'provinceid' => '31TTT'],
            ['districtid' => '315HH', 'name' => 'Huyện Tiên Lãng', 'provinceid' => '31TTT'],
            ['districtid' => '316HH', 'name' => 'Huyện Vĩnh Bảo', 'provinceid' => '31TTT'],
            ['districtid' => '317HH', 'name' => 'Huyện Cát Hải', 'provinceid' => '31TTT'],
            ['districtid' => '318HH', 'name' => 'Huyện Bạch Long Vĩ', 'provinceid' => '31TTT'],
            ['districtid' => '323HH', 'name' => 'Thành phố Hưng Yên', 'provinceid' => '33TTT'],
            ['districtid' => '325HH', 'name' => 'Huyện Văn Lâm', 'provinceid' => '33TTT'],
            ['districtid' => '326HH', 'name' => 'Huyện Văn Giang', 'provinceid' => '33TTT'],
            ['districtid' => '327HH', 'name' => 'Huyện Yên Mỹ', 'provinceid' => '33TTT'],
            ['districtid' => '328HH', 'name' => 'Huyện Mỹ Hào', 'provinceid' => '33TTT'],
            ['districtid' => '329HH', 'name' => 'Huyện Ân Thi', 'provinceid' => '33TTT'],
            ['districtid' => '330HH', 'name' => 'Huyện Khoái Châu', 'provinceid' => '33TTT'],
            ['districtid' => '331HH', 'name' => 'Huyện Kim Động', 'provinceid' => '33TTT'],
            ['districtid' => '332HH', 'name' => 'Huyện Tiên Lữ', 'provinceid' => '33TTT'],
            ['districtid' => '333HH', 'name' => 'Huyện Phù Cừ', 'provinceid' => '33TTT'],
            ['districtid' => '336HH', 'name' => 'Thành phố Thái Bình', 'provinceid' => '34TTT'],
            ['districtid' => '338HH', 'name' => 'Huyện Quỳnh Phụ', 'provinceid' => '34TTT'],
            ['districtid' => '339HH', 'name' => 'Huyện Hưng Hà', 'provinceid' => '34TTT'],
            ['districtid' => '340HH', 'name' => 'Huyện Đông Hưng', 'provinceid' => '34TTT'],
            ['districtid' => '341HH', 'name' => 'Huyện Thái Thụy', 'provinceid' => '34TTT'],
            ['districtid' => '342HH', 'name' => 'Huyện Tiền Hải', 'provinceid' => '34TTT'],
            ['districtid' => '343HH', 'name' => 'Huyện Kiến Xương', 'provinceid' => '34TTT'],
            ['districtid' => '344HH', 'name' => 'Huyện Vũ Thư', 'provinceid' => '34TTT'],
            ['districtid' => '347HH', 'name' => 'Thành phố Phủ Lý', 'provinceid' => '35TTT'],
            ['districtid' => '349HH', 'name' => 'Huyện Duy Tiên', 'provinceid' => '35TTT'],
            ['districtid' => '350HH', 'name' => 'Huyện Kim Bảng', 'provinceid' => '35TTT'],
            ['districtid' => '351HH', 'name' => 'Huyện Thanh Liêm', 'provinceid' => '35TTT'],
            ['districtid' => '352HH', 'name' => 'Huyện Bình Lục', 'provinceid' => '35TTT'],
            ['districtid' => '353HH', 'name' => 'Huyện Lý Nhân', 'provinceid' => '35TTT'],
            ['districtid' => '356HH', 'name' => 'Thành phố Nam Định', 'provinceid' => '36TTT'],
            ['districtid' => '358HH', 'name' => 'Huyện Mỹ Lộc', 'provinceid' => '36TTT'],
            ['districtid' => '359HH', 'name' => 'Huyện Vụ Bản', 'provinceid' => '36TTT'],
            ['districtid' => '360HH', 'name' => 'Huyện Ý Yên', 'provinceid' => '36TTT'],
            ['districtid' => '361HH', 'name' => 'Huyện Nghĩa Hưng', 'provinceid' => '36TTT'],
            ['districtid' => '362HH', 'name' => 'Huyện Nam Trực', 'provinceid' => '36TTT'],
            ['districtid' => '363HH', 'name' => 'Huyện Trực Ninh', 'provinceid' => '36TTT'],
            ['districtid' => '364HH', 'name' => 'Huyện Xuân Trường', 'provinceid' => '36TTT'],
            ['districtid' => '365HH', 'name' => 'Huyện Giao Thủy', 'provinceid' => '36TTT'],
            ['districtid' => '366HH', 'name' => 'Huyện Hải Hậu', 'provinceid' => '36TTT'],
            ['districtid' => '369HH', 'name' => 'Thành phố Ninh Bình', 'provinceid' => '37TTT'],
            ['districtid' => '370HH', 'name' => 'Thành phố Tam Điệp', 'provinceid' => '37TTT'],
            ['districtid' => '372HH', 'name' => 'Huyện Nho Quan', 'provinceid' => '37TTT'],
            ['districtid' => '373HH', 'name' => 'Huyện Gia Viễn', 'provinceid' => '37TTT'],
            ['districtid' => '374HH', 'name' => 'Huyện Hoa Lư', 'provinceid' => '37TTT'],
            ['districtid' => '375HH', 'name' => 'Huyện Yên Khánh', 'provinceid' => '37TTT'],
            ['districtid' => '376HH', 'name' => 'Huyện Kim Sơn', 'provinceid' => '37TTT'],
            ['districtid' => '377HH', 'name' => 'Huyện Yên Mô', 'provinceid' => '37TTT'],
            ['districtid' => '380HH', 'name' => 'Thành phố Thanh Hóa', 'provinceid' => '38TTT'],
            ['districtid' => '381HH', 'name' => 'Thị xã Bỉm Sơn', 'provinceid' => '38TTT'],
            ['districtid' => '382HH', 'name' => 'Thành phố Sầm Sơn', 'provinceid' => '38TTT'],
            ['districtid' => '384HH', 'name' => 'Huyện Mường Lát', 'provinceid' => '38TTT'],
            ['districtid' => '385HH', 'name' => 'Huyện Quan Hóa', 'provinceid' => '38TTT'],
            ['districtid' => '386HH', 'name' => 'Huyện Bá Thước', 'provinceid' => '38TTT'],
            ['districtid' => '387HH', 'name' => 'Huyện Quan Sơn', 'provinceid' => '38TTT'],
            ['districtid' => '388HH', 'name' => 'Huyện Lang Chánh', 'provinceid' => '38TTT'],
            ['districtid' => '389HH', 'name' => 'Huyện Ngọc Lặc', 'provinceid' => '38TTT'],
            ['districtid' => '390HH', 'name' => 'Huyện Cẩm Thủy', 'provinceid' => '38TTT'],
            ['districtid' => '391HH', 'name' => 'Huyện Thạch Thành', 'provinceid' => '38TTT'],
            ['districtid' => '392HH', 'name' => 'Huyện Hà Trung', 'provinceid' => '38TTT'],
            ['districtid' => '393HH', 'name' => 'Huyện Vĩnh Lộc', 'provinceid' => '38TTT'],
            ['districtid' => '394HH', 'name' => 'Huyện Yên Định', 'provinceid' => '38TTT'],
            ['districtid' => '395HH', 'name' => 'Huyện Thọ Xuân', 'provinceid' => '38TTT'],
            ['districtid' => '396HH', 'name' => 'Huyện Thường Xuân', 'provinceid' => '38TTT'],
            ['districtid' => '397HH', 'name' => 'Huyện Triệu Sơn', 'provinceid' => '38TTT'],
            ['districtid' => '398HH', 'name' => 'Huyện Thiệu Hóa', 'provinceid' => '38TTT'],
            ['districtid' => '399HH', 'name' => 'Huyện Hoằng Hóa', 'provinceid' => '38TTT'],
            ['districtid' => '400HH', 'name' => 'Huyện Hậu Lộc', 'provinceid' => '38TTT'],
            ['districtid' => '401HH', 'name' => 'Huyện Nga Sơn', 'provinceid' => '38TTT'],
            ['districtid' => '402HH', 'name' => 'Huyện Như Xuân', 'provinceid' => '38TTT'],
            ['districtid' => '403HH', 'name' => 'Huyện Như Thanh', 'provinceid' => '38TTT'],
            ['districtid' => '404HH', 'name' => 'Huyện Nông Cống', 'provinceid' => '38TTT'],
            ['districtid' => '405HH', 'name' => 'Huyện Đông Sơn', 'provinceid' => '38TTT'],
            ['districtid' => '406HH', 'name' => 'Huyện Quảng Xương', 'provinceid' => '38TTT'],
            ['districtid' => '407HH', 'name' => 'Huyện Tĩnh Gia', 'provinceid' => '38TTT'],
            ['districtid' => '412HH', 'name' => 'Thành phố Vinh', 'provinceid' => '40TTT'],
            ['districtid' => '413HH', 'name' => 'Thị xã Cửa Lò', 'provinceid' => '40TTT'],
            ['districtid' => '414HH', 'name' => 'Thị xã Thái Hòa', 'provinceid' => '40TTT'],
            ['districtid' => '415HH', 'name' => 'Huyện Quế Phong', 'provinceid' => '40TTT'],
            ['districtid' => '416HH', 'name' => 'Huyện Quỳ Châu', 'provinceid' => '40TTT'],
            ['districtid' => '417HH', 'name' => 'Huyện Kỳ Sơn', 'provinceid' => '40TTT'],
            ['districtid' => '418HH', 'name' => 'Huyện Tương Dương', 'provinceid' => '40TTT'],
            ['districtid' => '419HH', 'name' => 'Huyện Nghĩa Đàn', 'provinceid' => '40TTT'],
            ['districtid' => '420HH', 'name' => 'Huyện Quỳ Hợp', 'provinceid' => '40TTT'],
            ['districtid' => '421HH', 'name' => 'Huyện Quỳnh Lưu', 'provinceid' => '40TTT'],
            ['districtid' => '422HH', 'name' => 'Huyện Con Cuông', 'provinceid' => '40TTT'],
            ['districtid' => '423HH', 'name' => 'Huyện Tân Kỳ', 'provinceid' => '40TTT'],
            ['districtid' => '424HH', 'name' => 'Huyện Anh Sơn', 'provinceid' => '40TTT'],
            ['districtid' => '425HH', 'name' => 'Huyện Diễn Châu', 'provinceid' => '40TTT'],
            ['districtid' => '426HH', 'name' => 'Huyện Yên Thành', 'provinceid' => '40TTT'],
            ['districtid' => '427HH', 'name' => 'Huyện Đô Lương', 'provinceid' => '40TTT'],
            ['districtid' => '428HH', 'name' => 'Huyện Thanh Chương', 'provinceid' => '40TTT'],
            ['districtid' => '429HH', 'name' => 'Huyện Nghi Lộc', 'provinceid' => '40TTT'],
            ['districtid' => '430HH', 'name' => 'Huyện Nam Đàn', 'provinceid' => '40TTT'],
            ['districtid' => '431HH', 'name' => 'Huyện Hưng Nguyên', 'provinceid' => '40TTT'],
            ['districtid' => '432HH', 'name' => 'Thị xã Hoàng Mai', 'provinceid' => '40TTT'],
            ['districtid' => '436HH', 'name' => 'Thành phố Hà Tĩnh', 'provinceid' => '42TTT'],
            ['districtid' => '437HH', 'name' => 'Thị xã Hồng Lĩnh', 'provinceid' => '42TTT'],
            ['districtid' => '439HH', 'name' => 'Huyện Hương Sơn', 'provinceid' => '42TTT'],
            ['districtid' => '440HH', 'name' => 'Huyện Đức Thọ', 'provinceid' => '42TTT'],
            ['districtid' => '441HH', 'name' => 'Huyện Vũ Quang', 'provinceid' => '42TTT'],
            ['districtid' => '442HH', 'name' => 'Huyện Nghi Xuân', 'provinceid' => '42TTT'],
            ['districtid' => '443HH', 'name' => 'Huyện Can Lộc', 'provinceid' => '42TTT'],
            ['districtid' => '444HH', 'name' => 'Huyện Hương Khê', 'provinceid' => '42TTT'],
            ['districtid' => '445HH', 'name' => 'Huyện Thạch Hà', 'provinceid' => '42TTT'],
            ['districtid' => '446HH', 'name' => 'Huyện Cẩm Xuyên', 'provinceid' => '42TTT'],
            ['districtid' => '447HH', 'name' => 'Huyện Kỳ Anh', 'provinceid' => '42TTT'],
            ['districtid' => '448HH', 'name' => 'Huyện Lộc Hà', 'provinceid' => '42TTT'],
            ['districtid' => '449HH', 'name' => 'Thị xã Kỳ Anh', 'provinceid' => '42TTT'],
            ['districtid' => '450HH', 'name' => 'Thành Phố Đồng Hới', 'provinceid' => '44TTT'],
            ['districtid' => '452HH', 'name' => 'Huyện Minh Hóa', 'provinceid' => '44TTT'],
            ['districtid' => '453HH', 'name' => 'Huyện Tuyên Hóa', 'provinceid' => '44TTT'],
            ['districtid' => '454HH', 'name' => 'Huyện Quảng Trạch', 'provinceid' => '44TTT'],
            ['districtid' => '455HH', 'name' => 'Huyện Bố Trạch', 'provinceid' => '44TTT'],
            ['districtid' => '456HH', 'name' => 'Huyện Quảng Ninh', 'provinceid' => '44TTT'],
            ['districtid' => '457HH', 'name' => 'Huyện Lệ Thủy', 'provinceid' => '44TTT'],
            ['districtid' => '458HH', 'name' => 'Thị xã Ba Đồn', 'provinceid' => '44TTT'],
            ['districtid' => '461HH', 'name' => 'Thành phố Đông Hà', 'provinceid' => '45TTT'],
            ['districtid' => '462HH', 'name' => 'Thị xã Quảng Trị', 'provinceid' => '45TTT'],
            ['districtid' => '464HH', 'name' => 'Huyện Vĩnh Linh', 'provinceid' => '45TTT'],
            ['districtid' => '465HH', 'name' => 'Huyện Hướng Hóa', 'provinceid' => '45TTT'],
            ['districtid' => '466HH', 'name' => 'Huyện Gio Linh', 'provinceid' => '45TTT'],
            ['districtid' => '467HH', 'name' => 'Huyện Đakrông', 'provinceid' => '45TTT'],
            ['districtid' => '468HH', 'name' => 'Huyện Cam Lộ', 'provinceid' => '45TTT'],
            ['districtid' => '469HH', 'name' => 'Huyện Triệu Phong', 'provinceid' => '45TTT'],
            ['districtid' => '470HH', 'name' => 'Huyện Hải Lăng', 'provinceid' => '45TTT'],
            ['districtid' => '474HH', 'name' => 'Thành phố Huế', 'provinceid' => '46TTT'],
            ['districtid' => '476HH', 'name' => 'Huyện Phong Điền', 'provinceid' => '46TTT'],
            ['districtid' => '477HH', 'name' => 'Huyện Quảng Điền', 'provinceid' => '46TTT'],
            ['districtid' => '478HH', 'name' => 'Huyện Phú Vang', 'provinceid' => '46TTT'],
            ['districtid' => '479HH', 'name' => 'Thị xã Hương Thủy', 'provinceid' => '46TTT'],
            ['districtid' => '480HH', 'name' => 'Thị xã Hương Trà', 'provinceid' => '46TTT'],
            ['districtid' => '481HH', 'name' => 'Huyện A Lưới', 'provinceid' => '46TTT'],
            ['districtid' => '482HH', 'name' => 'Huyện Phú Lộc', 'provinceid' => '46TTT'],
            ['districtid' => '483HH', 'name' => 'Huyện Nam Đông', 'provinceid' => '46TTT'],
            ['districtid' => '490HH', 'name' => 'Quận Liên Chiểu', 'provinceid' => '48TTT'],
            ['districtid' => '491HH', 'name' => 'Quận Thanh Khê', 'provinceid' => '48TTT'],
            ['districtid' => '492HH', 'name' => 'Quận Hải Châu', 'provinceid' => '48TTT'],
            ['districtid' => '493HH', 'name' => 'Quận Sơn Trà', 'provinceid' => '48TTT'],
            ['districtid' => '494HH', 'name' => 'Quận Ngũ Hành Sơn', 'provinceid' => '48TTT'],
            ['districtid' => '495HH', 'name' => 'Quận Cẩm Lệ', 'provinceid' => '48TTT'],
            ['districtid' => '497HH', 'name' => 'Huyện Hòa Vang', 'provinceid' => '48TTT'],
            ['districtid' => '502HH', 'name' => 'Thành phố Tam Kỳ', 'provinceid' => '49TTT'],
            ['districtid' => '503HH', 'name' => 'Thành phố Hội An', 'provinceid' => '49TTT'],
            ['districtid' => '504HH', 'name' => 'Huyện Tây Giang', 'provinceid' => '49TTT'],
            ['districtid' => '505HH', 'name' => 'Huyện Đông Giang', 'provinceid' => '49TTT'],
            ['districtid' => '506HH', 'name' => 'Huyện Đại Lộc', 'provinceid' => '49TTT'],
            ['districtid' => '507HH', 'name' => 'Thị xã Điện Bàn', 'provinceid' => '49TTT'],
            ['districtid' => '508HH', 'name' => 'Huyện Duy Xuyên', 'provinceid' => '49TTT'],
            ['districtid' => '509HH', 'name' => 'Huyện Quế Sơn', 'provinceid' => '49TTT'],
            ['districtid' => '510HH', 'name' => 'Huyện Nam Giang', 'provinceid' => '49TTT'],
            ['districtid' => '511HH', 'name' => 'Huyện Phước Sơn', 'provinceid' => '49TTT'],
            ['districtid' => '512HH', 'name' => 'Huyện Hiệp Đức', 'provinceid' => '49TTT'],
            ['districtid' => '513HH', 'name' => 'Huyện Thăng Bình', 'provinceid' => '49TTT'],
            ['districtid' => '514HH', 'name' => 'Huyện Tiên Phước', 'provinceid' => '49TTT'],
            ['districtid' => '515HH', 'name' => 'Huyện Bắc Trà My', 'provinceid' => '49TTT'],
            ['districtid' => '516HH', 'name' => 'Huyện Nam Trà My', 'provinceid' => '49TTT'],
            ['districtid' => '517HH', 'name' => 'Huyện Núi Thành', 'provinceid' => '49TTT'],
            ['districtid' => '518HH', 'name' => 'Huyện Phú Ninh', 'provinceid' => '49TTT'],
            ['districtid' => '519HH', 'name' => 'Huyện Nông Sơn', 'provinceid' => '49TTT'],
            ['districtid' => '522HH', 'name' => 'Thành phố Quảng Ngãi', 'provinceid' => '51TTT'],
            ['districtid' => '524HH', 'name' => 'Huyện Bình Sơn', 'provinceid' => '51TTT'],
            ['districtid' => '525HH', 'name' => 'Huyện Trà Bồng', 'provinceid' => '51TTT'],
            ['districtid' => '526HH', 'name' => 'Huyện Tây Trà', 'provinceid' => '51TTT'],
            ['districtid' => '527HH', 'name' => 'Huyện Sơn Tịnh', 'provinceid' => '51TTT'],
            ['districtid' => '528HH', 'name' => 'Huyện Tư Nghĩa', 'provinceid' => '51TTT'],
            ['districtid' => '529HH', 'name' => 'Huyện Sơn Hà', 'provinceid' => '51TTT'],
            ['districtid' => '530HH', 'name' => 'Huyện Sơn Tây', 'provinceid' => '51TTT'],
            ['districtid' => '531HH', 'name' => 'Huyện Minh Long', 'provinceid' => '51TTT'],
            ['districtid' => '532HH', 'name' => 'Huyện Nghĩa Hành', 'provinceid' => '51TTT'],
            ['districtid' => '533HH', 'name' => 'Huyện Mộ Đức', 'provinceid' => '51TTT'],
            ['districtid' => '534HH', 'name' => 'Huyện Đức Phổ', 'provinceid' => '51TTT'],
            ['districtid' => '535HH', 'name' => 'Huyện Ba Tơ', 'provinceid' => '51TTT'],
            ['districtid' => '536HH', 'name' => 'Huyện Lý Sơn', 'provinceid' => '51TTT'],
            ['districtid' => '540HH', 'name' => 'Thành phố Quy Nhơn', 'provinceid' => '52TTT'],
            ['districtid' => '542HH', 'name' => 'Huyện An Lão', 'provinceid' => '52TTT'],
            ['districtid' => '543HH', 'name' => 'Huyện Hoài Nhơn', 'provinceid' => '52TTT'],
            ['districtid' => '544HH', 'name' => 'Huyện Hoài Ân', 'provinceid' => '52TTT'],
            ['districtid' => '545HH', 'name' => 'Huyện Phù Mỹ', 'provinceid' => '52TTT'],
            ['districtid' => '546HH', 'name' => 'Huyện Vĩnh Thạnh', 'provinceid' => '52TTT'],
            ['districtid' => '547HH', 'name' => 'Huyện Tây Sơn', 'provinceid' => '52TTT'],
            ['districtid' => '548HH', 'name' => 'Huyện Phù Cát', 'provinceid' => '52TTT'],
            ['districtid' => '549HH', 'name' => 'Thị xã An Nhơn', 'provinceid' => '52TTT'],
            ['districtid' => '550HH', 'name' => 'Huyện Tuy Phước', 'provinceid' => '52TTT'],
            ['districtid' => '551HH', 'name' => 'Huyện Vân Canh', 'provinceid' => '52TTT'],
            ['districtid' => '555HH', 'name' => 'Thành phố Tuy Hòa', 'provinceid' => '54TTT'],
            ['districtid' => '557HH', 'name' => 'Thị xã Sông Cầu', 'provinceid' => '54TTT'],
            ['districtid' => '558HH', 'name' => 'Huyện Đồng Xuân', 'provinceid' => '54TTT'],
            ['districtid' => '559HH', 'name' => 'Huyện Tuy An', 'provinceid' => '54TTT'],
            ['districtid' => '560HH', 'name' => 'Huyện Sơn Hòa', 'provinceid' => '54TTT'],
            ['districtid' => '561HH', 'name' => 'Huyện Sông Hinh', 'provinceid' => '54TTT'],
            ['districtid' => '562HH', 'name' => 'Huyện Tây Hòa', 'provinceid' => '54TTT'],
            ['districtid' => '563HH', 'name' => 'Huyện Phú Hòa', 'provinceid' => '54TTT'],
            ['districtid' => '564HH', 'name' => 'Huyện Đông Hòa', 'provinceid' => '54TTT'],
            ['districtid' => '568HH', 'name' => 'Thành phố Nha Trang', 'provinceid' => '56TTT'],
            ['districtid' => '569HH', 'name' => 'Thành phố Cam Ranh', 'provinceid' => '56TTT'],
            ['districtid' => '570HH', 'name' => 'Huyện Cam Lâm', 'provinceid' => '56TTT'],
            ['districtid' => '571HH', 'name' => 'Huyện Vạn Ninh', 'provinceid' => '56TTT'],
            ['districtid' => '572HH', 'name' => 'Thị xã Ninh Hòa', 'provinceid' => '56TTT'],
            ['districtid' => '573HH', 'name' => 'Huyện Khánh Vĩnh', 'provinceid' => '56TTT'],
            ['districtid' => '574HH', 'name' => 'Huyện Diên Khánh', 'provinceid' => '56TTT'],
            ['districtid' => '575HH', 'name' => 'Huyện Khánh Sơn', 'provinceid' => '56TTT'],
            ['districtid' => '576HH', 'name' => 'Huyện Trường Sa', 'provinceid' => '56TTT'],
            ['districtid' => '582HH', 'name' => 'Thành phố Phan Rang-Tháp Chàm', 'provinceid' => '58TTT'],
            ['districtid' => '584HH', 'name' => 'Huyện Bác Ái', 'provinceid' => '58TTT'],
            ['districtid' => '585HH', 'name' => 'Huyện Ninh Sơn', 'provinceid' => '58TTT'],
            ['districtid' => '586HH', 'name' => 'Huyện Ninh Hải', 'provinceid' => '58TTT'],
            ['districtid' => '587HH', 'name' => 'Huyện Ninh Phước', 'provinceid' => '58TTT'],
            ['districtid' => '588HH', 'name' => 'Huyện Thuận Bắc', 'provinceid' => '58TTT'],
            ['districtid' => '589HH', 'name' => 'Huyện Thuận Nam', 'provinceid' => '58TTT'],
            ['districtid' => '593HH', 'name' => 'Thành phố Phan Thiết', 'provinceid' => '60TTT'],
            ['districtid' => '594HH', 'name' => 'Thị xã La Gi', 'provinceid' => '60TTT'],
            ['districtid' => '595HH', 'name' => 'Huyện Tuy Phong', 'provinceid' => '60TTT'],
            ['districtid' => '596HH', 'name' => 'Huyện Bắc Bình', 'provinceid' => '60TTT'],
            ['districtid' => '597HH', 'name' => 'Huyện Hàm Thuận Bắc', 'provinceid' => '60TTT'],
            ['districtid' => '598HH', 'name' => 'Huyện Hàm Thuận Nam', 'provinceid' => '60TTT'],
            ['districtid' => '599HH', 'name' => 'Huyện Tánh Linh', 'provinceid' => '60TTT'],
            ['districtid' => '600HH', 'name' => 'Huyện Đức Linh', 'provinceid' => '60TTT'],
            ['districtid' => '601HH', 'name' => 'Huyện Hàm Tân', 'provinceid' => '60TTT'],
            ['districtid' => '602HH', 'name' => 'Huyện Phú Quí', 'provinceid' => '60TTT'],
            ['districtid' => '608HH', 'name' => 'Thành phố Kon Tum', 'provinceid' => '62TTT'],
            ['districtid' => '610HH', 'name' => 'Huyện Đắk Glei', 'provinceid' => '62TTT'],
            ['districtid' => '611HH', 'name' => 'Huyện Ngọc Hồi', 'provinceid' => '62TTT'],
            ['districtid' => '612HH', 'name' => 'Huyện Đắk Tô', 'provinceid' => '62TTT'],
            ['districtid' => '613HH', 'name' => 'Huyện Kon Plông', 'provinceid' => '62TTT'],
            ['districtid' => '614HH', 'name' => 'Huyện Kon Rẫy', 'provinceid' => '62TTT'],
            ['districtid' => '615HH', 'name' => 'Huyện Đắk Hà', 'provinceid' => '62TTT'],
            ['districtid' => '616HH', 'name' => 'Huyện Sa Thầy', 'provinceid' => '62TTT'],
            ['districtid' => '617HH', 'name' => 'Huyện Tu Mơ Rông', 'provinceid' => '62TTT'],
            ['districtid' => '618HH', 'name' => 'Huyện Ia H Drai', 'provinceid' => '62TTT'],
            ['districtid' => '622HH', 'name' => 'Thành phố Pleiku', 'provinceid' => '64TTT'],
            ['districtid' => '623HH', 'name' => 'Thị xã An Khê', 'provinceid' => '64TTT'],
            ['districtid' => '624HH', 'name' => 'Thị xã Ayun Pa', 'provinceid' => '64TTT'],
            ['districtid' => '625HH', 'name' => 'Huyện KBang', 'provinceid' => '64TTT'],
            ['districtid' => '626HH', 'name' => 'Huyện Đăk Đoa', 'provinceid' => '64TTT'],
            ['districtid' => '627HH', 'name' => 'Huyện Chư Păh', 'provinceid' => '64TTT'],
            ['districtid' => '628HH', 'name' => 'Huyện Ia Grai', 'provinceid' => '64TTT'],
            ['districtid' => '629HH', 'name' => 'Huyện Mang Yang', 'provinceid' => '64TTT'],
            ['districtid' => '630HH', 'name' => 'Huyện Kông Chro', 'provinceid' => '64TTT'],
            ['districtid' => '631HH', 'name' => 'Huyện Đức Cơ', 'provinceid' => '64TTT'],
            ['districtid' => '632HH', 'name' => 'Huyện Chư Prông', 'provinceid' => '64TTT'],
            ['districtid' => '633HH', 'name' => 'Huyện Chư Sê', 'provinceid' => '64TTT'],
            ['districtid' => '634HH', 'name' => 'Huyện Đăk Pơ', 'provinceid' => '64TTT'],
            ['districtid' => '635HH', 'name' => 'Huyện Ia Pa', 'provinceid' => '64TTT'],
            ['districtid' => '637HH', 'name' => 'Huyện Krông Pa', 'provinceid' => '64TTT'],
            ['districtid' => '638HH', 'name' => 'Huyện Phú Thiện', 'provinceid' => '64TTT'],
            ['districtid' => '639HH', 'name' => 'Huyện Chư Pưh', 'provinceid' => '64TTT'],
            ['districtid' => '643HH', 'name' => 'Thành phố Buôn Ma Thuột', 'provinceid' => '66TTT'],
            ['districtid' => '644HH', 'name' => 'Thị Xã Buôn Hồ', 'provinceid' => '66TTT'],
            ['districtid' => '645HH', 'name' => 'Huyện Ea H leo', 'provinceid' => '66TTT'],
            ['districtid' => '646HH', 'name' => 'Huyện Ea Súp', 'provinceid' => '66TTT'],
            ['districtid' => '647HH', 'name' => 'Huyện Buôn Đôn', 'provinceid' => '66TTT'],
            ['districtid' => '648HH', 'name' => 'Huyện Cư M gar', 'provinceid' => '66TTT'],
            ['districtid' => '649HH', 'name' => 'Huyện Krông Búk', 'provinceid' => '66TTT'],
            ['districtid' => '650HH', 'name' => 'Huyện Krông Năng', 'provinceid' => '66TTT'],
            ['districtid' => '651HH', 'name' => 'Huyện Ea Kar', 'provinceid' => '66TTT'],
            ['districtid' => '652HH', 'name' => 'Huyện M Đrắk', 'provinceid' => '66TTT'],
            ['districtid' => '653HH', 'name' => 'Huyện Krông Bông', 'provinceid' => '66TTT'],
            ['districtid' => '654HH', 'name' => 'Huyện Krông Pắc', 'provinceid' => '66TTT'],
            ['districtid' => '655HH', 'name' => 'Huyện Krông A Na', 'provinceid' => '66TTT'],
            ['districtid' => '656HH', 'name' => 'Huyện Lắk', 'provinceid' => '66TTT'],
            ['districtid' => '657HH', 'name' => 'Huyện Cư Kuin', 'provinceid' => '66TTT'],
            ['districtid' => '660HH', 'name' => 'Thị xã Gia Nghĩa', 'provinceid' => '67TTT'],
            ['districtid' => '661HH', 'name' => 'Huyện Đăk Glong', 'provinceid' => '67TTT'],
            ['districtid' => '662HH', 'name' => 'Huyện Cư Jút', 'provinceid' => '67TTT'],
            ['districtid' => '663HH', 'name' => 'Huyện Đắk Mil', 'provinceid' => '67TTT'],
            ['districtid' => '664HH', 'name' => 'Huyện Krông Nô', 'provinceid' => '67TTT'],
            ['districtid' => '665HH', 'name' => 'Huyện Đắk Song', 'provinceid' => '67TTT'],
            ['districtid' => '666HH', 'name' => 'Huyện Đắk RLấp', 'provinceid' => '67TTT'],
            ['districtid' => '667HH', 'name' => 'Huyện Tuy Đức', 'provinceid' => '67TTT'],
            ['districtid' => '672HH', 'name' => 'Thành phố Đà Lạt', 'provinceid' => '68TTT'],
            ['districtid' => '673HH', 'name' => 'Thành phố Bảo Lộc', 'provinceid' => '68TTT'],
            ['districtid' => '674HH', 'name' => 'Huyện Đam Rông', 'provinceid' => '68TTT'],
            ['districtid' => '675HH', 'name' => 'Huyện Lạc Dương', 'provinceid' => '68TTT'],
            ['districtid' => '676HH', 'name' => 'Huyện Lâm Hà', 'provinceid' => '68TTT'],
            ['districtid' => '677HH', 'name' => 'Huyện Đơn Dương', 'provinceid' => '68TTT'],
            ['districtid' => '678HH', 'name' => 'Huyện Đức Trọng', 'provinceid' => '68TTT'],
            ['districtid' => '679HH', 'name' => 'Huyện Di Linh', 'provinceid' => '68TTT'],
            ['districtid' => '680HH', 'name' => 'Huyện Bảo Lâm', 'provinceid' => '68TTT'],
            ['districtid' => '681HH', 'name' => 'Huyện Đạ Huoai', 'provinceid' => '68TTT'],
            ['districtid' => '682HH', 'name' => 'Huyện Đạ Tẻh', 'provinceid' => '68TTT'],
            ['districtid' => '683HH', 'name' => 'Huyện Cát Tiên', 'provinceid' => '68TTT'],
            ['districtid' => '688HH', 'name' => 'Thị xã Phước Long', 'provinceid' => '70TTT'],
            ['districtid' => '689HH', 'name' => 'Thị xã Đồng Xoài', 'provinceid' => '70TTT'],
            ['districtid' => '690HH', 'name' => 'Thị xã Bình Long', 'provinceid' => '70TTT'],
            ['districtid' => '691HH', 'name' => 'Huyện Bù Gia Mập', 'provinceid' => '70TTT'],
            ['districtid' => '692HH', 'name' => 'Huyện Lộc Ninh', 'provinceid' => '70TTT'],
            ['districtid' => '693HH', 'name' => 'Huyện Bù Đốp', 'provinceid' => '70TTT'],
            ['districtid' => '694HH', 'name' => 'Huyện Hớn Quản', 'provinceid' => '70TTT'],
            ['districtid' => '695HH', 'name' => 'Huyện Đồng Phú', 'provinceid' => '70TTT'],
            ['districtid' => '696HH', 'name' => 'Huyện Bù Đăng', 'provinceid' => '70TTT'],
            ['districtid' => '697HH', 'name' => 'Huyện Chơn Thành', 'provinceid' => '70TTT'],
            ['districtid' => '698HH', 'name' => 'Huyện Phú Riềng', 'provinceid' => '70TTT'],
            ['districtid' => '703HH', 'name' => 'Thành phố Tây Ninh', 'provinceid' => '72TTT'],
            ['districtid' => '705HH', 'name' => 'Huyện Tân Biên', 'provinceid' => '72TTT'],
            ['districtid' => '706HH', 'name' => 'Huyện Tân Châu', 'provinceid' => '72TTT'],
            ['districtid' => '707HH', 'name' => 'Huyện Dương Minh Châu', 'provinceid' => '72TTT'],
            ['districtid' => '708HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '72TTT'],
            ['districtid' => '709HH', 'name' => 'Huyện Hòa Thành', 'provinceid' => '72TTT'],
            ['districtid' => '710HH', 'name' => 'Huyện Gò Dầu', 'provinceid' => '72TTT'],
            ['districtid' => '711HH', 'name' => 'Huyện Bến Cầu', 'provinceid' => '72TTT'],
            ['districtid' => '712HH', 'name' => 'Huyện Trảng Bàng', 'provinceid' => '72TTT'],
            ['districtid' => '718HH', 'name' => 'Thành phố Thủ Dầu Một', 'provinceid' => '74TTT'],
            ['districtid' => '719HH', 'name' => 'Huyện Bàu Bàng', 'provinceid' => '74TTT'],
            ['districtid' => '720HH', 'name' => 'Huyện Dầu Tiếng', 'provinceid' => '74TTT'],
            ['districtid' => '721HH', 'name' => 'Thị xã Bến Cát', 'provinceid' => '74TTT'],
            ['districtid' => '722HH', 'name' => 'Huyện Phú Giáo', 'provinceid' => '74TTT'],
            ['districtid' => '723HH', 'name' => 'Thị xã Tân Uyên', 'provinceid' => '74TTT'],
            ['districtid' => '724HH', 'name' => 'Thị xã Dĩ An', 'provinceid' => '74TTT'],
            ['districtid' => '725HH', 'name' => 'Thị xã Thuận An', 'provinceid' => '74TTT'],
            ['districtid' => '726HH', 'name' => 'Huyện Bắc Tân Uyên', 'provinceid' => '74TTT'],
            ['districtid' => '731HH', 'name' => 'Thành phố Biên Hòa', 'provinceid' => '75TTT'],
            ['districtid' => '732HH', 'name' => 'Thị xã Long Khánh', 'provinceid' => '75TTT'],
            ['districtid' => '734HH', 'name' => 'Huyện Tân Phú', 'provinceid' => '75TTT'],
            ['districtid' => '735HH', 'name' => 'Huyện Vĩnh Cửu', 'provinceid' => '75TTT'],
            ['districtid' => '736HH', 'name' => 'Huyện Định Quán', 'provinceid' => '75TTT'],
            ['districtid' => '737HH', 'name' => 'Huyện Trảng Bom', 'provinceid' => '75TTT'],
            ['districtid' => '738HH', 'name' => 'Huyện Thống Nhất', 'provinceid' => '75TTT'],
            ['districtid' => '739HH', 'name' => 'Huyện Cẩm Mỹ', 'provinceid' => '75TTT'],
            ['districtid' => '740HH', 'name' => 'Huyện Long Thành', 'provinceid' => '75TTT'],
            ['districtid' => '741HH', 'name' => 'Huyện Xuân Lộc', 'provinceid' => '75TTT'],
            ['districtid' => '742HH', 'name' => 'Huyện Nhơn Trạch', 'provinceid' => '75TTT'],
            ['districtid' => '747HH', 'name' => 'Thành phố Vũng Tàu', 'provinceid' => '77TTT'],
            ['districtid' => '748HH', 'name' => 'Thành phố Bà Rịa', 'provinceid' => '77TTT'],
            ['districtid' => '750HH', 'name' => 'Huyện Châu Đức', 'provinceid' => '77TTT'],
            ['districtid' => '751HH', 'name' => 'Huyện Xuyên Mộc', 'provinceid' => '77TTT'],
            ['districtid' => '752HH', 'name' => 'Huyện Long Điền', 'provinceid' => '77TTT'],
            ['districtid' => '753HH', 'name' => 'Huyện Đất Đỏ', 'provinceid' => '77TTT'],
            ['districtid' => '754HH', 'name' => 'Huyện Tân Thành', 'provinceid' => '77TTT'],
            ['districtid' => '755HH', 'name' => 'Huyện Côn Đảo', 'provinceid' => '77TTT'],
            ['districtid' => '760HH', 'name' => 'Quận 1', 'provinceid' => '79TTT'],
            ['districtid' => '761HH', 'name' => 'Quận 12', 'provinceid' => '79TTT'],
            ['districtid' => '762HH', 'name' => 'Quận Thủ Đức', 'provinceid' => '79TTT'],
            ['districtid' => '763HH', 'name' => 'Quận 9', 'provinceid' => '79TTT'],
            ['districtid' => '764HH', 'name' => 'Quận Gò Vấp', 'provinceid' => '79TTT'],
            ['districtid' => '765HH', 'name' => 'Quận Bình Thạnh', 'provinceid' => '79TTT'],
            ['districtid' => '766HH', 'name' => 'Quận Tân Bình', 'provinceid' => '79TTT'],
            ['districtid' => '767HH', 'name' => 'Quận Tân Phú', 'provinceid' => '79TTT'],
            ['districtid' => '768HH', 'name' => 'Quận Phú Nhuận', 'provinceid' => '79TTT'],
            ['districtid' => '769HH', 'name' => 'Quận 2', 'provinceid' => '79TTT'],
            ['districtid' => '770HH', 'name' => 'Quận 3', 'provinceid' => '79TTT'],
            ['districtid' => '771HH', 'name' => 'Quận 10', 'provinceid' => '79TTT'],
            ['districtid' => '772HH', 'name' => 'Quận 11', 'provinceid' => '79TTT'],
            ['districtid' => '773HH', 'name' => 'Quận 4', 'provinceid' => '79TTT'],
            ['districtid' => '774HH', 'name' => 'Quận 5', 'provinceid' => '79TTT'],
            ['districtid' => '775HH', 'name' => 'Quận 6', 'provinceid' => '79TTT'],
            ['districtid' => '776HH', 'name' => 'Quận 8', 'provinceid' => '79TTT'],
            ['districtid' => '777HH', 'name' => 'Quận Bình Tân', 'provinceid' => '79TTT'],
            ['districtid' => '778HH', 'name' => 'Quận 7', 'provinceid' => '79TTT'],
            ['districtid' => '783HH', 'name' => 'Huyện Củ Chi', 'provinceid' => '79TTT'],
            ['districtid' => '784HH', 'name' => 'Huyện Hóc Môn', 'provinceid' => '79TTT'],
            ['districtid' => '785HH', 'name' => 'Huyện Bình Chánh', 'provinceid' => '79TTT'],
            ['districtid' => '786HH', 'name' => 'Huyện Nhà Bè', 'provinceid' => '79TTT'],
            ['districtid' => '787HH', 'name' => 'Huyện Cần Giờ', 'provinceid' => '79TTT'],
            ['districtid' => '794HH', 'name' => 'Thành phố Tân An', 'provinceid' => '80TTT'],
            ['districtid' => '795HH', 'name' => 'Thị xã Kiến Tường', 'provinceid' => '80TTT'],
            ['districtid' => '796HH', 'name' => 'Huyện Tân Hưng', 'provinceid' => '80TTT'],
            ['districtid' => '797HH', 'name' => 'Huyện Vĩnh Hưng', 'provinceid' => '80TTT'],
            ['districtid' => '798HH', 'name' => 'Huyện Mộc Hóa', 'provinceid' => '80TTT'],
            ['districtid' => '799HH', 'name' => 'Huyện Tân Thạnh', 'provinceid' => '80TTT'],
            ['districtid' => '800HH', 'name' => 'Huyện Thạnh Hóa', 'provinceid' => '80TTT'],
            ['districtid' => '801HH', 'name' => 'Huyện Đức Huệ', 'provinceid' => '80TTT'],
            ['districtid' => '802HH', 'name' => 'Huyện Đức Hòa', 'provinceid' => '80TTT'],
            ['districtid' => '803HH', 'name' => 'Huyện Bến Lức', 'provinceid' => '80TTT'],
            ['districtid' => '804HH', 'name' => 'Huyện Thủ Thừa', 'provinceid' => '80TTT'],
            ['districtid' => '805HH', 'name' => 'Huyện Tân Trụ', 'provinceid' => '80TTT'],
            ['districtid' => '806HH', 'name' => 'Huyện Cần Đước', 'provinceid' => '80TTT'],
            ['districtid' => '807HH', 'name' => 'Huyện Cần Giuộc', 'provinceid' => '80TTT'],
            ['districtid' => '808HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '80TTT'],
            ['districtid' => '815HH', 'name' => 'Thành phố Mỹ Tho', 'provinceid' => '82TTT'],
            ['districtid' => '816HH', 'name' => 'Thị xã Gò Công', 'provinceid' => '82TTT'],
            ['districtid' => '817HH', 'name' => 'Thị xã Cai Lậy', 'provinceid' => '82TTT'],
            ['districtid' => '818HH', 'name' => 'Huyện Tân Phước', 'provinceid' => '82TTT'],
            ['districtid' => '819HH', 'name' => 'Huyện Cái Bè', 'provinceid' => '82TTT'],
            ['districtid' => '820HH', 'name' => 'Huyện Cai Lậy', 'provinceid' => '82TTT'],
            ['districtid' => '821HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '82TTT'],
            ['districtid' => '822HH', 'name' => 'Huyện Chợ Gạo', 'provinceid' => '82TTT'],
            ['districtid' => '823HH', 'name' => 'Huyện Gò Công Tây', 'provinceid' => '82TTT'],
            ['districtid' => '824HH', 'name' => 'Huyện Gò Công Đông', 'provinceid' => '82TTT'],
            ['districtid' => '825HH', 'name' => 'Huyện Tân Phú Đông', 'provinceid' => '82TTT'],
            ['districtid' => '829HH', 'name' => 'Thành phố Bến Tre', 'provinceid' => '83TTT'],
            ['districtid' => '831HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '83TTT'],
            ['districtid' => '832HH', 'name' => 'Huyện Chợ Lách', 'provinceid' => '83TTT'],
            ['districtid' => '833HH', 'name' => 'Huyện Mỏ Cày Nam', 'provinceid' => '83TTT'],
            ['districtid' => '834HH', 'name' => 'Huyện Giồng Trôm', 'provinceid' => '83TTT'],
            ['districtid' => '835HH', 'name' => 'Huyện Bình Đại', 'provinceid' => '83TTT'],
            ['districtid' => '836HH', 'name' => 'Huyện Ba Tri', 'provinceid' => '83TTT'],
            ['districtid' => '837HH', 'name' => 'Huyện Thạnh Phú', 'provinceid' => '83TTT'],
            ['districtid' => '838HH', 'name' => 'Huyện Mỏ Cày Bắc', 'provinceid' => '83TTT'],
            ['districtid' => '842HH', 'name' => 'Thành phố Trà Vinh', 'provinceid' => '84TTT'],
            ['districtid' => '844HH', 'name' => 'Huyện Càng Long', 'provinceid' => '84TTT'],
            ['districtid' => '845HH', 'name' => 'Huyện Cầu Kè', 'provinceid' => '84TTT'],
            ['districtid' => '846HH', 'name' => 'Huyện Tiểu Cần', 'provinceid' => '84TTT'],
            ['districtid' => '847HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '84TTT'],
            ['districtid' => '848HH', 'name' => 'Huyện Cầu Ngang', 'provinceid' => '84TTT'],
            ['districtid' => '849HH', 'name' => 'Huyện Trà Cú', 'provinceid' => '84TTT'],
            ['districtid' => '850HH', 'name' => 'Huyện Duyên Hải', 'provinceid' => '84TTT'],
            ['districtid' => '851HH', 'name' => 'Thị xã Duyên Hải', 'provinceid' => '84TTT'],
            ['districtid' => '855HH', 'name' => 'Thành phố Vĩnh Long', 'provinceid' => '86TTT'],
            ['districtid' => '857HH', 'name' => 'Huyện Long Hồ', 'provinceid' => '86TTT'],
            ['districtid' => '858HH', 'name' => 'Huyện Mang Thít', 'provinceid' => '86TTT'],
            ['districtid' => '859HH', 'name' => 'Huyện Vũng Liêm', 'provinceid' => '86TTT'],
            ['districtid' => '860HH', 'name' => 'Huyện Tam Bình', 'provinceid' => '86TTT'],
            ['districtid' => '861HH', 'name' => 'Thị xã Bình Minh', 'provinceid' => '86TTT'],
            ['districtid' => '862HH', 'name' => 'Huyện Trà Ôn', 'provinceid' => '86TTT'],
            ['districtid' => '863HH', 'name' => 'Huyện Bình Tân', 'provinceid' => '86TTT'],
            ['districtid' => '866HH', 'name' => 'Thành phố Cao Lãnh', 'provinceid' => '87TTT'],
            ['districtid' => '867HH', 'name' => 'Thành phố Sa Đéc', 'provinceid' => '87TTT'],
            ['districtid' => '868HH', 'name' => 'Thị xã Hồng Ngự', 'provinceid' => '87TTT'],
            ['districtid' => '869HH', 'name' => 'Huyện Tân Hồng', 'provinceid' => '87TTT'],
            ['districtid' => '870HH', 'name' => 'Huyện Hồng Ngự', 'provinceid' => '87TTT'],
            ['districtid' => '871HH', 'name' => 'Huyện Tam Nông', 'provinceid' => '87TTT'],
            ['districtid' => '872HH', 'name' => 'Huyện Tháp Mười', 'provinceid' => '87TTT'],
            ['districtid' => '873HH', 'name' => 'Huyện Cao Lãnh', 'provinceid' => '87TTT'],
            ['districtid' => '874HH', 'name' => 'Huyện Thanh Bình', 'provinceid' => '87TTT'],
            ['districtid' => '875HH', 'name' => 'Huyện Lấp Vò', 'provinceid' => '87TTT'],
            ['districtid' => '876HH', 'name' => 'Huyện Lai Vung', 'provinceid' => '87TTT'],
            ['districtid' => '877HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '87TTT'],
            ['districtid' => '883HH', 'name' => 'Thành phố Long Xuyên', 'provinceid' => '89TTT'],
            ['districtid' => '884HH', 'name' => 'Thành phố Châu Đốc', 'provinceid' => '89TTT'],
            ['districtid' => '886HH', 'name' => 'Huyện An Phú', 'provinceid' => '89TTT'],
            ['districtid' => '887HH', 'name' => 'Thị xã Tân Châu', 'provinceid' => '89TTT'],
            ['districtid' => '888HH', 'name' => 'Huyện Phú Tân', 'provinceid' => '89TTT'],
            ['districtid' => '889HH', 'name' => 'Huyện Châu Phú', 'provinceid' => '89TTT'],
            ['districtid' => '890HH', 'name' => 'Huyện Tịnh Biên', 'provinceid' => '89TTT'],
            ['districtid' => '891HH', 'name' => 'Huyện Tri Tôn', 'provinceid' => '89TTT'],
            ['districtid' => '892HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '89TTT'],
            ['districtid' => '893HH', 'name' => 'Huyện Chợ Mới', 'provinceid' => '89TTT'],
            ['districtid' => '894HH', 'name' => 'Huyện Thoại Sơn', 'provinceid' => '89TTT'],
            ['districtid' => '899HH', 'name' => 'Thành phố Rạch Giá', 'provinceid' => '91TTT'],
            ['districtid' => '900HH', 'name' => 'Thị xã Hà Tiên', 'provinceid' => '91TTT'],
            ['districtid' => '902HH', 'name' => 'Huyện Kiên Lương', 'provinceid' => '91TTT'],
            ['districtid' => '903HH', 'name' => 'Huyện Hòn Đất', 'provinceid' => '91TTT'],
            ['districtid' => '904HH', 'name' => 'Huyện Tân Hiệp', 'provinceid' => '91TTT'],
            ['districtid' => '905HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '91TTT'],
            ['districtid' => '906HH', 'name' => 'Huyện Giồng Riềng', 'provinceid' => '91TTT'],
            ['districtid' => '907HH', 'name' => 'Huyện Gò Quao', 'provinceid' => '91TTT'],
            ['districtid' => '908HH', 'name' => 'Huyện An Biên', 'provinceid' => '91TTT'],
            ['districtid' => '909HH', 'name' => 'Huyện An Minh', 'provinceid' => '91TTT'],
            ['districtid' => '910HH', 'name' => 'Huyện Vĩnh Thuận', 'provinceid' => '91TTT'],
            ['districtid' => '911HH', 'name' => 'Huyện Phú Quốc', 'provinceid' => '91TTT'],
            ['districtid' => '912HH', 'name' => 'Huyện Kiên Hải', 'provinceid' => '91TTT'],
            ['districtid' => '913HH', 'name' => 'Huyện U Minh Thượng', 'provinceid' => '91TTT'],
            ['districtid' => '914HH', 'name' => 'Huyện Giang Thành', 'provinceid' => '91TTT'],
            ['districtid' => '916HH', 'name' => 'Quận Ninh Kiều', 'provinceid' => '92TTT'],
            ['districtid' => '917HH', 'name' => 'Quận Ô Môn', 'provinceid' => '92TTT'],
            ['districtid' => '918HH', 'name' => 'Quận Bình Thuỷ', 'provinceid' => '92TTT'],
            ['districtid' => '919HH', 'name' => 'Quận Cái Răng', 'provinceid' => '92TTT'],
            ['districtid' => '923HH', 'name' => 'Quận Thốt Nốt', 'provinceid' => '92TTT'],
            ['districtid' => '924HH', 'name' => 'Huyện Vĩnh Thạnh', 'provinceid' => '92TTT'],
            ['districtid' => '925HH', 'name' => 'Huyện Cờ Đỏ', 'provinceid' => '92TTT'],
            ['districtid' => '926HH', 'name' => 'Huyện Phong Điền', 'provinceid' => '92TTT'],
            ['districtid' => '927HH', 'name' => 'Huyện Thới Lai', 'provinceid' => '92TTT'],
            ['districtid' => '930HH', 'name' => 'Thành phố Vị Thanh', 'provinceid' => '93TTT'],
            ['districtid' => '931HH', 'name' => 'Thị xã Ngã Bảy', 'provinceid' => '93TTT'],
            ['districtid' => '932HH', 'name' => 'Huyện Châu Thành A', 'provinceid' => '93TTT'],
            ['districtid' => '933HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '93TTT'],
            ['districtid' => '934HH', 'name' => 'Huyện Phụng Hiệp', 'provinceid' => '93TTT'],
            ['districtid' => '935HH', 'name' => 'Huyện Vị Thủy', 'provinceid' => '93TTT'],
            ['districtid' => '936HH', 'name' => 'Huyện Long Mỹ', 'provinceid' => '93TTT'],
            ['districtid' => '937HH', 'name' => 'Thị xã Long Mỹ', 'provinceid' => '93TTT'],
            ['districtid' => '941HH', 'name' => 'Thành phố Sóc Trăng', 'provinceid' => '94TTT'],
            ['districtid' => '942HH', 'name' => 'Huyện Châu Thành', 'provinceid' => '94TTT'],
            ['districtid' => '943HH', 'name' => 'Huyện Kế Sách', 'provinceid' => '94TTT'],
            ['districtid' => '944HH', 'name' => 'Huyện Mỹ Tú', 'provinceid' => '94TTT'],
            ['districtid' => '945HH', 'name' => 'Huyện Cù Lao Dung', 'provinceid' => '94TTT'],
            ['districtid' => '946HH', 'name' => 'Huyện Long Phú', 'provinceid' => '94TTT'],
            ['districtid' => '947HH', 'name' => 'Huyện Mỹ Xuyên', 'provinceid' => '94TTT'],
            ['districtid' => '948HH', 'name' => 'Thị xã Ngã Năm', 'provinceid' => '94TTT'],
            ['districtid' => '949HH', 'name' => 'Huyện Thạnh Trị', 'provinceid' => '94TTT'],
            ['districtid' => '950HH', 'name' => 'Thị xã Vĩnh Châu', 'provinceid' => '94TTT'],
            ['districtid' => '951HH', 'name' => 'Huyện Trần Đề', 'provinceid' => '94TTT'],
            ['districtid' => '954HH', 'name' => 'Thành phố Bạc Liêu', 'provinceid' => '95TTT'],
            ['districtid' => '956HH', 'name' => 'Huyện Hồng Dân', 'provinceid' => '95TTT'],
            ['districtid' => '957HH', 'name' => 'Huyện Phước Long', 'provinceid' => '95TTT'],
            ['districtid' => '958HH', 'name' => 'Huyện Vĩnh Lợi', 'provinceid' => '95TTT'],
            ['districtid' => '959HH', 'name' => 'Thị xã Giá Rai', 'provinceid' => '95TTT'],
            ['districtid' => '960HH', 'name' => 'Huyện Đông Hải', 'provinceid' => '95TTT'],
            ['districtid' => '961HH', 'name' => 'Huyện Hòa Bình', 'provinceid' => '95TTT'],
            ['districtid' => '964HH', 'name' => 'Thành phố Cà Mau', 'provinceid' => '96TTT'],
            ['districtid' => '966HH', 'name' => 'Huyện U Minh', 'provinceid' => '96TTT'],
            ['districtid' => '967HH', 'name' => 'Huyện Thới Bình', 'provinceid' => '96TTT'],
            ['districtid' => '968HH', 'name' => 'Huyện Trần Văn Thời', 'provinceid' => '96TTT'],
            ['districtid' => '969HH', 'name' => 'Huyện Cái Nước', 'provinceid' => '96TTT'],
            ['districtid' => '970HH', 'name' => 'Huyện Đầm Dơi', 'provinceid' => '96TTT'],
            ['districtid' => '971HH', 'name' => 'Huyện Năm Căn', 'provinceid' => '96TTT'],
            ['districtid' => '972HH', 'name' => 'Huyện Phú Tân', 'provinceid' => '96TTT'],
            ['districtid' => '973HH', 'name' => 'Huyện Ngọc Hiển', 'provinceid' => '96TTT']
        ]);

       
    }
}
